pipeline {
    agent any
    environment {
        MODE = "dev"
    }

    stages {
        stage('pre build') {
            steps {
                sh "rm -rf ./Dockerfile"
                sh "cp ./cicd/dev/Dockerfile ./Dockerfile"
                script {
                    tag = sh(script: "git tag -l | tail -1 | tr -d \'\\n\'", returnStdout: true)
                    docker_image_name = sh(script: "echo ${env.JOB_BASE_NAME} | tr -d \'\\n\'", returnStdout: true)
                }
            }
        }
        stage('print prebuild') {
            steps {
                echo "dockerimage:tag ${docker_image_name}:${tag}"
            }
        }
        stage('docker build and push') {
            steps {
                script {
                    docker.withRegistry("http://${REGISTRY}", "NEXUS_DOCKER_ID")  {
                        script {
                            customimage = docker.build "${docker_image_name}:${tag}"
                            customimage.push()
                            sh(script: "docker rmi ${REGISTRY}/${docker_image_name}:${tag}", returnStdout: true)
                        }
                    }
                }
            }
        }
        stage('checkout cicd branch') {
            steps {
                git branch: 'cicd', url: 'https://github.com/srmproject/Backend-python.git'
            }
        }
        stage('change image:tag') {
            steps {
                dir("dev") {
                    sh """
                    cat <<EOF > kustomization.yaml
                    bases:
                      - ../base

                    patches:
                      - target:
                          kind: Ingress
                          name: backend-python
                        patch: |-
                          - op: replace
                            path: /spec/rules/0/host
                            value: dev-backend.choilab.xyz

                    namePrefix: dev-

                    configurations:
                      - nameReference.yaml

                    commonLabels:
                      app: dev-backend-python

                    images:
                      - name: core-image
                        newName: ${REGISTRY}/${docker_image_name}
                        newTag: ${tag}

                    EOF
                    """.stripIndent()

                    withCredentials([sshUserPrivateKey(credentialsId: "JCP-FRONTEND-CORE-SSHKEY", keyFileVariable: "SSH_KEY")]) {
                        sh """
                            mkdir -p ~/.ssh
                            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
                            git add kustomization.yaml

                            git config --local user.email "myjenkins@admin.com"
                            git config --local user.name "jenkins"
                            git commit -m 'change image:tag'

                            git remote -v
                            git remote add target git@github.com:srmproject/Backend-python.git
                            GIT_SSH_COMMAND="ssh -i $SSH_KEY" git push target cicd
                            git remote remove target
                        """
                    }
                }
            }
        }
    }
}