from enum import Enum

class ErrorCode(str, Enum):
    CREATE_JOB_VALIDATION_NAME_IS_NOT_EXIST = "520"
    CREATE_JOB_VALIDATION_NAMESPACE_IS_NOT_EXIST = "521"
    CREATE_JOB_VALIDATION_PROJECT_IS_NOT_EXIST = "522"
    CREATE_JOB_VALIDATION_GITHUB_URL_INCORRECT_PREFIX = "524"
    CREATE_JOB_VALIDATION_GITHUB_URL_INCORRECT_POSTFIX = "525"
    CREATE_JOB_VALIDATION_GITHUB_URL_IS_NOT_EXIST = "526"
    CREATE_JOB_VALIDATION_GET_BRANCH_OTHER_EXCEPTION = "527"
    CREATE_JOB_DB_ERROR = "523"

