from enum import Enum

class ErrorCode(str, Enum):
    CREATE_JOB_VALIDATION_NAME = "520"
    CREATE_JOB_VALIDATION_NAMESPACE = "521"
    CREATE_JOB_VALIDATION_PROJECT_IS_NOT_EXIST = "522"
    CREATE_JOB_DB_ERROR = "523"
